listen: "0.0.0.0:5555"
sprites_dir: internal/resources/sprites
teams:
  - name: "Test"
    snapshots_path:
      - "/Users/jnovikov/ctfdev/ctfcup-2024-igra/snapshots"
rounds:
  - level: "test"
    start: "2022-12-13T00:00:00"
